name: HTML5 Validator
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Python 3.10.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      - name: Upgrade Pip
        run: |
          pip install --upgrade pip
      - name: Cache/Uncache npm dependencies
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          cd src
          npm install
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Validate HTML + CSS Files
        run: |
          html5validator --blacklist assets/
