name: HTML5 Validater
on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Yarn + Install Dependencies
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
        run: yarn install
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with: 
          distribution: 'temurin'
          java-version: '8'
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
      - name: Upgrade Pip
        run: |
          pip install --upgrade pip
      - name: Upgrade Setuptools + Wheel
        run: |
          pip install --upgrade setuptools wheel
      - name: Install HTML5 Validator
        run: |
          pip install html5validator
      - name: Validate HTML + CSS Files
        run: |
          html5vaildator index.html --root _Lesson-1/ --also-check-css