name: Prettier
on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install Yarn Dependencies
        run: |
          yarn install
      - name: Format with Prettier
        run: |
          yarn prettier --write Lessons/
