name: Prettier
on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm dependencies
        run: |
          cd src
          npm install
      - name: Format with Prettier
        run: |
          cd src
          npx prettier --ignore-path .prettierignore --write . 
      - name: Commit And Push All Changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Format All HTML + CSS Files'
          add: 'src/ --all'
          push: true
          branch: master
          pull: '--no-rebase'
